language: ruby
rvm:
  - 2.3.0
addons:
  postgresql: '9.3'
bundler_args: "--without production --jobs=3"
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database-travis.yml config/database.yml
  - bundle exec rake db:schema:load RAILS_ENV=test
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rspec spec
  - bundle exec rspec spec -t slow
  - bundle exec rake spec:javascript
