db:
  image: postgres
api:
  image: pivotalsingapore/spotlight-rails
  command: bin/rails server
  env_file: docker_env
  links:
    - db
web:
  image: pivotalsingapore/spotlight-dashboard
  env_file: docker_env
  ports:
    - "3030:80"
  links:
    - api
