---
resources:
  - name: spotlight-git
    type: git
    source:
      uri: git@github.com:pivotal-sg/spotlight.git
      branch: master
      private_key: {{git-private-key}}

  - name: spotlight-test-image
    type: docker-image
    source:
      repository: pivotalsingapore/spotlight-tests
      email: {{docker-email}}
      username: {{docker-username}}
      password: {{docker-password}}

  - name: spotlight-rails-deploy-image
    type: docker-image
    source:
      repository: pivotalsingapore/spotlight-rails
      email: {{docker-email}}
      username: {{docker-username}}
      password: {{docker-password}}

jobs:
  - name: build-test-image
    public: false
    serial: true
    plan:
      - get: spotlight-git
        trigger: true
      - put: spotlight-test-image
        params:
          build: spotlight-git/
          dockerfile: spotlight-git/Dockerfile.tests
          cache: true

  - name: tests
    public: true
    plan:
      - get: spotlight-git
        passed: [build-test-image]
      - get: spotlight-test-image
        passed: [build-test-image]
        trigger: true
      - task: unit-rb
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalsingapore/spotlight-tests
          run:
            path: /code/run-tests-in-docker.sh
            args: [rb]

  - name: build-deployment-image
    public: false
    plan:
      - get: spotlight-git
        trigger: true
        passed: [tests]
      - put: spotlight-rails-deploy-image
        params:
          build: spotlight-git/
          dockerfile: spotlight-git/Dockerfile
          cache: true
